# -*- coding: utf-8 -*-
"""pandas3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7CJ3drSeqzWV5QX0_wwQW0GC2Fizsz9
"""

import pandas as pd
dictionary = {"name":["ahmet","samet","zeliha","sinem","berat","canan"],
             "age":[12,34,56,78,None,12],
             "note":[123,456,78,87654,None,89]}

dataframe1 = pd.DataFrame(dictionary) 
print(dataframe1)

head = dataframe1.head()
print(head)
print("-------------------------")
print(dataframe1.columns)
print("-------------------------")
print(dataframe1.info())
print("-------------------------")
print(dataframe1.dtypes)
print("-------------------------")
print(dataframe1.describe())
print("-------------------------")

print(dataframe1["name"])
print("-------------------------")
print(dataframe1.loc[:, "age"])
print("-------------------------")
dataframe1["yeni_future"] = [1,2,3,4,5,6]
print(dataframe1.loc[:3,"age"])
print("-------------------------")
print(dataframe1.loc[:3, "name":"note"])
print("-------------------------")
print(dataframe1.loc[::-1])
print("-------------------------")

filtre1 = dataframe1.age>10
dataframe1["bool"] = filtre1
print(dataframe1.loc[:,["age","bool"]])

filtre2 = dataframe1.note>100
filtrelenmis_data2 = dataframe1[filtre2&filtre1]
print(filtrelenmis_data2)

dataframe1.dropna(inplace=True)
dataframe1

dataframe1["situation"]= ["below average" if dataframe1.note.mean()>each else "above average" for each in dataframe1.note]
dataframe1

dataframe1["yeni2_future"]=[1,1,1,1,1]
dataframe1.columns = [each.split('_')[0]+" "+each.split('_')[1] if len(each.split('_'))>1 else each for each in dataframe1.columns]
dataframe1

dataframe1.columns = [each.upper() for each in dataframe1.columns]
dataframe1.columns

data1 = dataframe1.head()
data2 = dataframe1.tail()
data_concat = pd.concat([data1,data2],axis=0)
data_concat

dataframe1["new_age"] = [each*2 for each in dataframe1.AGE]

def mlt(yas):
  return yas*2
dataframe1["apply_metodu"] = dataframe1.AGE.apply(mlt)
dataframe1