# -*- coding: utf-8 -*-
"""py_hafta1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CEceQo8g5vXQBet8uOICJXzcAraqCe4H
"""

print("Hello Python")

def sum(val1,val2):  # sum adında bir fonksiyon tanımladık.
  sum=val1+val2
  return sum

sum(12,23) # 12 ve 23 parametreleri girerek sum fonksiyonunu çağırdık.

myList = [1, 2, 3, 4, 5, 6, 7, 8]
print(myList)
print(myList[0:3]) # 0. indisten 3. indise kadar yazar.
print(myList[0:9:2]) # 0. indisten 9. indise kadar 2 şer atlayarak yazar.
print(myList[::-1]) # tersten yazdırır. 1 azaltarak.
min(myList) #listenin minimum değerini yazdırır.

myList.append(12) # diziye yeni eleman ekler.
print(myList)

myList.reverse() # diziyi tersten yazdırır.
print(myList)

myList.sort() #kücükten büyüğe sıralar
print(myList)

value1 = 14
type(value1)

value2 = 13.21
type(value2)

type(myList)

list2 = ["selam",24,"naber",23] #listeler string int karısık degerler alabilir.
print(list2)

dictionary = {"ahmet":17, "can":21, "samet":25}

keys = dictionary.keys() #dictionary'nin keyleri keys variable'ına eşitlendi.

if "ahmet" in keys: #ahmet keylerin içindeyse evet, değilse hayır yazılır.

    print("evet")

else:
    print("hayır")

for each in range (2,10): #2 den 10 a kadar yazdırır. 10 hariç.
    
    print(each)

def alan_hesapla(val1,val2):
  alan=val1*val2
  return alan

alan_hesapla(10,5)