# -*- coding: utf-8 -*-
"""seaborn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwnSwg0i_4LcMUOBfuMKImBvAlElYDBz
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Örnek Veri 
data = sns.load_dataset("flights")
data = data.pivot("month", "year", "passengers")

# Heatmap
sns.heatmap(data=data, annot=True, fmt="d", cmap="YlGnBu")

plt.show()

data.info

import seaborn as sns 
import matplotlib.pyplot as plt

# Örnek Veri 
data = sns.load_dataset("flights")

# Line Plot
sns.lineplot(data=data, x="year", y="passengers")

plt.show()

import seaborn as sns 
import matplotlib.pyplot as plt

data = sns.load_dataset("iris")

sns.swarmplot(x="species", y="petal_length", data=data)

plt.show()

import seaborn as sns 
import matplotlib.pyplot as plt

data = sns.load_dataset("titanic")

sns.countplot(data=data, x="class")

plt.show()

import seaborn as sns 
import matplotlib.pyplot as plt

data = sns.load_dataset("tips")

sns.scatterplot(data=data, x="total_bill", y="tip")

plt.show()

import seaborn as sns 
import matplotlib.pyplot as plt

data = sns.load_dataset("titanic")

g = sns.FacetGrid(data, col="sex")

g.map(sns.histplot, "age")

plt.show()

import seaborn as sns 

iris = sns.load_dataset("iris")

g = sns.clustermap(iris.drop("species", axis=1), cmap="coolwarm", standard_scale=1)

plt.show()

import seaborn as sns 
import matplotlib.pyplot as plt

data = sns.load_dataset("iris")

sns.histplot(data=data, x="sepal_length")

plt.show()

import seaborn as sns 
import matplotlib.pyplot as plt

data = sns.load_dataset("tips")

sns.violinplot(x="day", y="total_bill", data=data)

plt.show()

import seaborn as sns 
sns.set_theme(style="white")

df = sns.load_dataset("penguins")

g = sns.JointGrid(data=df, x="body_mass_g", y="bill_depth_mm", space=0)
g.plot_joint(sns.kdeplot,
             fill=True, clip=((2200, 6800), (10, 25)),
             thresh=0, levels=100, cmap="rocket")
g.plot_marginals(sns.histplot, color="#03051A", alpha=1, bins=25)

import seaborn as sns
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'age_group': np.repeat(['18-30', '31-45', '46-60', '61+'], 100),
    'feedback_rating': np.random.randint(1, 6, 400)
})
g = sns.FacetGrid(data, col="age_group", margin_titles=True)

g.map(sns.histplot, "feedback_rating")